spring:
  application:
    name: gateway-service
  cloud:
    client:
      hostname: localhost
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 9090

eureka:
  preferSameZone: false
  shouldUseDns: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
    intance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}

jwt:
  secret: secretkey