#spring:
#  application:
#    name: profile-service
#  data:
#    mongodb:
#      uri: mongodb+srv://satya:Satya@cluster0.01hmatw.mongodb.net/new?retryWrites=true&w=majority
#      database: new
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher
#server:
#  port: 8082
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8083/eureka
#  instance:
#    prefer-ip-address: true
#
#springdoc:
#  swagger-ui:
#    path: /profile-service-swagger.html
#  operationsSorter: method
#jwtSecret: secret
#jwtExpiration: 86400