#spring:
#  application:
#    name: product-service
#  cloud:
#    client:
#      hostname: localhost
#    gateway:
#      discovery:
#        locator:
#          lower-case-service-id: true
#          enabled: true
#  jackson:
#    default-property-inclusion: NON_NULL
#  data:
#    mongodb:
#      uri: mongodb+srv://satya:Satya@cluster0.01hmatw.mongodb.net/new?retryWrites=true&w=majority
#      database: new
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher
#
#
#server:
#  port: 8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8083/eureka
#  instance:
#    hostname: localhost
#    preferIpAddress: true
#    intance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
#
#springdoc:
#  swagger-ui:
#    path: /product-service-swagger.html
#  operationsSorter: method